feat: use fondue serializer for blocks
Frontify/brand-sdk pull request #504
Opened 2023-08-09 11:59 UTC by ragi96

If we go with https://github.com/Frontify/web-app/pull/945 we could remove the serializer here and all the hacky classes

2023-08-11 12:09 UTC, SamuelAlev commented
Please add a changeset

2023-08-11 14:38 UTC, SamuelAlev commented on .changeset/cyan-ghosts-visit.md
> +feat(RTE): use fondue serializer
```suggestion
refactor: use Fondue serializer instead of internal version
```

2023-08-28 10:42 UTC, SamuelAlev approved these changes

2023-08-28 11:04 UTC, SamuelAlev requested changes
On hold as it actually seems to break blocks

2023-08-29 07:35 UTC, ragi96 commented
> On hold as it actually seems to break blocks

Not related to the changes in this PR, as it breaks (just linked) within the linkPlugin and buttonPlugin. 

A workaround is to use it within blocks as workspace package then it doesn't break. Also with version 0.28.4 it doesn't break, just linked is an issue.

2023-08-29 07:56 UTC, fulopdaniel approved these changes

2023-08-30 12:46 UTC, merged