feat: Add bulk download command
Frontify/brand-sdk pull request #633
Opened 2023-11-15 18:24 UTC by utmishra

- Adds `downloadAssetsInBulk` logic as a _Command_
    - This simply downloads the assets from the provided URL, while also tracking the _Asset download_ event
- [Implementation PR](https://github.com/Frontify/web-app/compare/feat/bulk-download-tracking)

2023-11-17 10:43 UTC, fulopdaniel approved these changes
Don't forget to add a changeset

2023-11-18 14:20 UTC, SamuelAlev commented on packages/app-bridge/src/AppBridgeBlock.ts
> +        | 'downloadAssetsInBulk'
`downloadAssets` if you pluralize it, it infers it is in bulk.

2023-11-18 14:20 UTC, SamuelAlev requested changes
`downloadAssets` if you pluralize it, it infers it is in bulk.

2023-11-18 14:20 UTC, SamuelAlev commented on packages/app-bridge/src/AppBridgeBlock.ts
> +        | 'downloadAssetsInBulk'
```suggestion
        | 'downloadAssets'
```
`downloadAssets` if you pluralize it, it infers it is in bulk.

2023-11-20 16:33 UTC, utmishra commented
> `downloadAssets` if you pluralize it, it infers it is in bulk.

@SamuelAlev Renamed in interface and [implementation](https://github.com/Frontify/web-app/pull/2037)

2023-11-28 10:52 UTC, olivereisenhut commented on .changeset/serious-books-watch.md
> +Added `downloadAssets` Command to trigger download for Bulk Assets
I think this is no longer needed.

2023-11-28 10:55 UTC, utmishra commented on .changeset/serious-books-watch.md
> +Added `downloadAssets` Command to trigger download for Bulk Assets
Removed 👍🏽

2023-11-28 11:09 UTC, utmishra commented
@olivereisenhut FYI: Missed the typecheck errors, fixing right now

2023-11-29 07:24 UTC, olivereisenhut approved these changes

2023-11-29 09:47 UTC, SamuelAlev commented on packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts
>      documentBlockId: number;
Same comment as [here](https://github.com/Frontify/web-app/pull/2037#discussion_r1409019508), users shouldn't have to know the block ID.

2023-11-29 09:47 UTC, SamuelAlev commented on packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts
> +import { Asset } from '../../types';
```suggestion
import type { Asset } from '../../types';
```

2023-11-29 16:17 UTC, SamuelAlev commented on packages/app-bridge/src/tests/AppBridgeBlockStub.ts
> +    stubbedInstance['api'] = stub<Parameters<AppBridgeBlock['api']>>()
define `const apiStubs = stub[...]` instead of this

2023-11-29 16:17 UTC, SamuelAlev commented on packages/app-bridge/src/tests/AppBridgeBlockStub.ts
> +    const stubbedInstance = {
```suggestion
    return {
```

2023-11-29 16:17 UTC, SamuelAlev commented on packages/app-bridge/src/tests/AppBridgeBlockStub.ts
> +        api: stub<Parameters<AppBridgeBlock['api']>>().resolves(),
```suggestion
        api: apiStubs,
```

2023-12-04 13:46 UTC, SamuelAlev commented on packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts
> +import type { Asset } from '../..';
Prefer a direct path import if possible, avoid `from '.'` or `from '..'` or `from '../..'`, etc

2023-12-04 13:47 UTC, SamuelAlev commented on packages/app-bridge/src/react/useAssetBulkDownload.spec.tsx
>  import { AssetBulkDownloadState, useAssetBulkDownload } from './';
```suggestion
import { AssetBulkDownloadState, useAssetBulkDownload } from './useAssetBulkDownload';
```

2023-12-04 14:14 UTC, utmishra commented on packages/app-bridge/src/registries/api/GetAssetBulkDownloadToken.ts
> +import type { Asset } from '../..';
Importing from ` '../../types' now

2023-12-04 14:58 UTC, merged