feat(appBridge): Add proxyNetworkCall method (#821)
Frontify/brand-sdk pull request #838
Opened 2024-03-19 08:09 UTC by imoutaharik

* feat(PlatformApp): add new API method

* Update .changeset/clever-gifts-join.md

---------

2024-03-19 08:41 UTC, marguslant0 approved these changes
LGTM! 🎉

2024-03-19 10:43 UTC, anxobotana approved these changes
Owned files look good

2024-03-19 10:47 UTC, ragi96 approved these changes
Owned files are looking good

2024-03-20 13:48 UTC, ragi96 requested changes

2024-03-20 13:48 UTC, ragi96 commented on .changeset/four-cherries-beg.md
> +---
Remove that changeset, probably better to use a dedicated branch then `main` -> `dev` for the merge, as here could happen some issues

2024-03-21 07:28 UTC, imoutaharik commented
Closing this one and will do differently.

2024-03-21 07:28 UTC, closed without merging